services:
  - type: worker
    runtime: docker
    name: pganalyze-collector
    plan: starter
    region: oregon
    envVars:
      - key: PGA_API_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: PGA_ALWAYS_COLLECT_SYSTEM_DATA
        value: "1"